service: serveless-node-infra
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - "@aws-sdk/*"
    # define:
    #   require.resolve: undefined
    platform: node
    # concurrency: 10

functions:
  function1:
    handler: index.handler

plugins:
  - serverless-esbuild
  - serverless-offline
